default:
  image: $CI_REGISTRY/docker/zammad-ci:3.0.4

include:
  - local: '/.gitlab/ci/base.yml'
  - local: '/.gitlab/ci/pre.yml'
  - local: '/.gitlab/ci/integration.yml'
  - local: '/.gitlab/ci/rspec.yml'
  - local: '/.gitlab/ci/vitest.yml'
  - local: '/.gitlab/ci/cypress.yml'
  - local: '/.gitlab/ci/unit.yml'
  - local: '/.gitlab/ci/browser-core.yml'
  - local: '/.gitlab/ci/browser-integration.yml'

# Stages
stages:
  - pre
  - test
  - browser-core
  - browser-integration

# Global variables added to the ENV of each job
variables:
  # for faster translation loading
  Z_LOCALES: "en-us:de-de"
  # Browser tests and variables
  RAILS_SERVE_STATIC_FILES: "true"
  TZ: "Europe/London"
  # docker-imap-devel variables required for browser tests
  MAILNAME: "mail.test.dc.zammad.com"
  MAILBOX_INIT: "zammad@mail.test.dc.zammad.com:zammad"
  MAIL_ADDRESS: "zammad@mail.test.dc.zammad.com"
  MAIL_PASS: "zammad"
  # docker-imap-devel variables required for integration tests
  MAIL_SERVER: "mail"
  MAIL_SERVER_ACCOUNT: "zammad@mail.test.dc.zammad.com:zammad"
  MAIL_SERVER_EMAIL: "zammad@mail.test.dc.zammad.com"
  KEEP_ON_MAIL_SERVER: "mail"
  KEEP_ON_MAIL_SERVER_ACCOUNT: "zammad@mail.test.dc.zammad.com:zammad"
  # Temporary switch to enable the mobile front end for testing.
  ENABLE_EXPERIMENTAL_MOBILE_FRONTEND: 'true'
  # Compile assets only once.
  CI_SKIP_ASSETS_PRECOMPILE: 'true'

cache:
  # Cache gems in between jobs and pipelines
  - key:
      files:
        - Gemfile.lock
    paths:
      - vendor/ruby
      - fresh.env
  # Cache node_modules likewise
  - key:
      files:
        - yarn.lock
    paths:
      - .yarn/cache

# Initialize application env
before_script:
  - source /etc/profile.d/rvm.sh
  - echo -e "\\e[0Ksection_start:`date +%s`:bundle_install[collapsed=true]\\r\\e[0Kbundle install"
  - bundle config set --local frozen 'true'
  - bundle config set --local path 'vendor'
  - bundle install -j $(nproc)
  - echo -e "\\e[0Ksection_end:`date +%s`:bundle_install\\r\\e[0K"
  - bundle exec ruby .gitlab/configure_environment.rb
  - source .gitlab/environment.env

after_script:
  - .gitlab/environment_info.sh > log/environment_info.log